name: drupal-composer
recipe: drupal8
config:
  via: nginx
  php: '7.3'
  webroot: build/html
  database: mysql
  xdebug: true

env_file:
  -  .env

services:
  appserver:
    build:
      - composer install
    run:
      - /app/scripts/bash/install.sh
#  search:
#    type: solr
#    portforward: true
#  mail:
#    type: mailhog
#    portforward: true

tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/build/html"
  install:
    service: appserver
    cmd: /app/scripts/bash/install.sh
    description: Install Drupal
  pantheon-deploy:
    service: appserver
    cmd: /app/scripts/bash/pantheon-deploy.sh
    description: Deploy project to a Pantheon instance
