#!/usr/bin/env bash
# Install the Drupal site.
#: exec_target = cli

# Database for the drush command.
DB_URL="mysql://${DATABASE_USER:-user}:${DATABASE_PASSWORD:-user}@${DATABASE_HOST:-db}/${DATABASE_NAME:-default}"

# Install Drupal site
drush si --db-url=$DB_URL --account-pass="admin"  -y
