#!/usr/bin/env bash

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'
current_dir=${PWD##*/}

#-------------------------- Execution --------------------------------

# Get Project name
echo -e "${green}What's the project's name?${NC}"
read -p "[${current_dir}]: " NAME
NAME=${NAME:-${current_dir}}
#echo ${name,,}
SAFE_NAME="$(echo -e "${NAME,,}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
#SAFE_NAME1="$(${SAFE_NAME// /-})"
SAFE_NAME="$(echo -e "${SAFE_NAME// /-}")"


sed -i "s/drupal-composer/${SAFE_NAME}/g" $PWD/.docksal/docksal.env
sed -i "s/drupal-composer/${SAFE_NAME}/g" $PWD/.env.dist
